### ISSUE TITLE
Questions regarding the TinyVision board

### ISSUE THREAD

**Issue by mohnazemi** [YuzukiHD/TinyVision#18]
Hi @YuzukiTsuru 

I have a question regarding the TinyVison board. The features page suggests that the chip can encode videos using H.264/H.265 with frame resolutions of 3840x2160@20fps which is 8Mpixels, but the chip datasheet suggests it supports only up to 4Mpixels on CSI interface. Can you elaborate more on this?

Also, I wanted to order a Tinyvison board on Taobao to try it but it seems it is out of stock, so do you have any idea when it will be available again to order ?

Thanks for your help

**Comment by YuzukiTsuru** [comment]
The camera is 4M, but encoder is 3840x2160@20fps, Which means you can prepare a bunch of yuv data and code it to him instead of using the camera data. For the camera, it can also encode certain content after shooting, and the 4M here is only the limit of the camera rather than the limit of the encoder.

The first batch has been sold out, the second batch of goods is still in line for production, and the estimated time of the factory has not been determined

**Comment by mohnazemi** [comment]
Thanks for your response. I guess if the 4M limit is only the camera, then I guess in theory we can even use an 8MP camera at lower frame rates, as the MIPI CSI supports it ?

**Comment by YuzukiTsuru** [comment]
MIPI CSI limited by data link speed, V851se 1.2GHz per lane

**Comment by mohnazemi** [comment]
I think you mean 1.2Gbps per lane according to the datasheet, so with 4-lane MIPI you can have a total of 6Gbps transfers. So 3264x2448 Pixels (8M) x 30fps x 16 bits (YUYV) = ~3.9Gbps is then possible?
